---config
liveison=1;
simulation_maxnumhuman=588000;
simulation_mintimeadd=3600x20; ... 3600 = 1 hour
simulation_maxtimeadd=86400x7; ... 86400 = 1 day
simulation_limit_dies=500;
simulation_limit_couple=100;
simulation_limit_givingbirth=100;
starttimestamp=;
startdatetime=2000-01-01 00:00:00;
agecoupled=20,40; ... years
agedied=30,200; ... years
pregnant=7x1,365x10; ... days after coupled 
givingbirth=230,252; ... days after pregnant
agemenopause=50,60;
